config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords],  controllers: {
    sessions: "admin/sessions"
  }
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #delete 'admin/circuit_tracks/:id' => 'circuit_tracks#destroy'
  #delete 'admin/categories/:id' => 'categories#destroy'
  get 'posts/new/:category' => 'posts#new'
  namespace :admin do
    resources :posts
    resources :track_events
    resources :users
    resources :mycars
    resources :homes
    resources :parts
    resources :circuit_tracks
    resources :categories
  end
  
  
  scope module: :public do
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
      get :search, on: :collection
    end
    resources :track_events do
      patch 'update_deadline_event', on: :member
      get :search, on: :collection
    end
    
    patch 'track_events/:id/update_deadline_event', to: 'public/track_events#update_deadline_event', as: 'update_deadline_event'
    resources :users do
      resources :my_best_times
      member do
        post 'follow', to: 'users#follow', as: 'follow'
        post 'unfollow', to: 'users#unfollow', as: 'unfollow'
      end
    end
    resources :follows, only: [:create, :destroy]
    resources :mycars
    resources :homes
    resources :parts
    resources :circuit_tracks
    resources :categories
    resources :events do
      patch 'update_deadline', on: :member
    end

  end 
  root to: "public/homes#top"
  get 'about' => 'public/homes#about'
  get 'no_signin' => 'public/homes#no_signin'
  
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/circuit_track.rb
class CircuitTrack < ApplicationRecord
  has_one_attached :circuit_image
  
  has_many :users
  has_many :my_best_times
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  # belongs_to :track_event
  # belongs_to :part
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
  #belongs_to :user
end

app/models/home.rb
class Home < ApplicationRecord
  has_one_attached :image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/models/my_best_time.rb
class MyBestTime < ApplicationRecord
  belongs_to :user
  belongs_to :circuit_track
end

app/models/mycar.rb
class Mycar < ApplicationRecord
  has_one_attached :mycar_image
end

app/models/part.rb
class Part < ApplicationRecord
  has_one_attached :parts_image
  belongs_to :user
  # has_many :favorites, dependent: :destroy
  
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
end

app/models/track_event.rb
class TrackEvent < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  # has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :mycar_image
  
  has_many :posts, dependent: :destroy
  has_many :track_events, dependent: :destroy
  has_many :parts, dependent: :destroy
  has_many :my_best_times, dependent: :destroy
  belongs_to :circuit_track, optional: true, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  accepts_nested_attributes_for :my_best_times, allow_destroy: true
  
  has_many :follows, foreign_key: :follower_id, dependent: :destroy

  has_many :followings, through: :follows, source: :followed
  has_many :followers, through: :follows, source: :follower

  def follow(user)
    follows.create(followed_id: user.id)
  end

  def unfollow(user)
    followings.delete(user)
  end

  def following?(user)
    followings.include?(user)
  end
  
  def self.my_followers(user)
    follower_ids = Follow.where(followed_id: user.id).pluck(:follower_id)
    User.where(id: follower_ids)
  end
  
  def deleted?
    is_deleted
  end
  
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :nickname, presence: true
  
  enum main_circuit: { tukubacircuit: 0, fuji_speedway: 1, suzukacircuit: 2, twinringmotegi: 3 }
end

app/controllers/admin/circuit_tracks_controller.rb
class Admin::CircuitTracksController < ApplicationController
  def new
    @circuit_track = CircuitTrack.new
  end 
  def index
    @circuit_tracks = CircuitTrack.all
  end 
  def show
    @circuit_track = CircuitTrack.find(params[:id])
  end 
  def edit 
    @circuit_track = CircuitTrack.find(params[:id])
  end 
  def create
    @circuit_track = CircuitTrack.new(circuit_track_params)
    if @circuit_track.save
      redirect_to circuit_tracks_path, notice: '投稿が作成されました。'
    else
      render :new
    end
  end
  def update
    @circuit_track = CircuitTrack.find(params[:id])
    if @circuit_track.update(circuit_track_params)
      redirect_to circuit_track_path(@circuit_track)
    else
      render :edit
    end
  end 
  def destroy
    @circuit_track = CircuitTrack.find(params[:id])
    @circuit_track.destroy
    redirect_to circuit_tracks_path
  end
  
  private
  
  def circuit_track_params
    params.require(:circuit_track).permit(:name, :address, :circuit_image)
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :nickname, :address, :age, :mycar, :main_circuit, :freeprofile])
  end
end

app/helpers/admin/circuit_tracks_helper.rb
module Admin::CircuitTracksHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/mycars_helper.rb
module Admin::MycarsHelper
end

app/helpers/admin/parts_helper.rb
module Admin::PartsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/circuit_tracks/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="text-center text-white">サーキット編集</h1>

      <%= form_with model: @circuit_track, url: admin_circuit_track_path(@circuit_track), method: :patch, multipart: true do |f| %>
        <div class="form-group text-white">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group text-white">
          <%= f.label :address %>
          <%= f.text_area :address, class: "form-control" %>
        </div>

        <div class="form-group text-white">
          <%= f.label :circuit_image %>
          <%= f.file_field :circuit_image, class: "form-control-file" %>
        </div>

        <div class="text-center text-white">
          <%= f.submit '更新する', class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/circuit_tracks/index.html.erb
<h1>サーキット一覧</h1>

<h1><%= link_to "+", new_admin_circuit_track_path %></h1> 

<% @circuit_tracks.each do |ct| %>
<%= ct.name %>
<%= ct.address %>
<%= ct.circuit_image %>
<%= link_to "編集", edit_admin_category_path(ct.id) %>
<%= link_to "削除", admin_categories_path(ct.id), method: :delete, data: { confirm: "本当に削除しますか？" } %>
<% end %>


<h1>サーキット作成</h1>

<%= form_with model: @circuit_track, url: admin_circuit_tracks_path, multipart: true do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :address %>
    <%= f.text_area :address %>
  </div>

  <div>
    <%= f.label :circuit_image %>
    <%= f.file_field :circuit_image %>
  </div>

  <div>
    <%= f.submit '投稿する' %>
  </div>
<% end %>

app/views/admin/circuit_tracks/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="text-center text-white">サーキット作成</h1>

      <%= form_with model: @circuit_track, url: admin_circuit_tracks_path, multipart: true do |f| %>
        <div class="form-group text-white">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group text-white">
          <%= f.label :address %>
          <%= f.text_area :address, class: "form-control" %>
        </div>

        <div class="form-group text-white">
          <%= f.label :circuit_image %>
          <%= f.file_field :circuit_image, class: "form-control-file" %>
        </div>

        <div class="text-center text-white">
          <%= f.submit '投稿する', class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/circuit_tracks/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="text-center">サーキット詳細</h1>

      <h2><%= @circuit_track.name %></h2>

      <p><strong>住所:</strong> <%= @circuit_track.address %></p>

      <div class="text-center">
        <%= link_to '編集', edit_admin_circuit_track_path(@circuit_track), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>