config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords],  controllers: {
    sessions: "admin/sessions"
  }
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #delete 'admin/circuit_tracks/:id' => 'circuit_tracks#destroy'
  #delete 'admin/categories/:id' => 'categories#destroy'
  get 'posts/new/:category' => 'posts#new'
  namespace :admin do
    resources :posts
    resources :track_events
    resources :users
    resources :mycars
    resources :homes
    resources :parts
    resources :circuit_tracks
    resources :categories
  end
  
  
  scope module: :public do
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
      get :search, on: :collection
    end
    resources :track_events do
      patch 'update_deadline_event', on: :member
      get :search, on: :collection
    end
    
    patch 'track_events/:id/update_deadline_event', to: 'public/track_events#update_deadline_event', as: 'update_deadline_event'
    resources :users do
      resources :my_best_times
      member do
        post 'follow', to: 'users#follow', as: 'follow'
        post 'unfollow', to: 'users#unfollow', as: 'unfollow'
      end
    end
    resources :follows, only: [:create, :destroy]
    resources :mycars
    resources :homes
    resources :parts
    resources :circuit_tracks
    resources :categories
    resources :events do
      patch 'update_deadline', on: :member
    end

  end 
  root to: "public/homes#top"
  get 'about' => 'public/homes#about'
  get 'no_signin' => 'public/homes#no_signin'
  
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/circuit_track.rb
class CircuitTrack < ApplicationRecord
  has_one_attached :circuit_image
  
  has_many :users
  has_many :my_best_times
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  # belongs_to :track_event
  # belongs_to :part
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
  #belongs_to :user
end

app/models/home.rb
class Home < ApplicationRecord
  has_one_attached :image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/models/my_best_time.rb
class MyBestTime < ApplicationRecord
  belongs_to :user
  belongs_to :circuit_track
end

app/models/mycar.rb
class Mycar < ApplicationRecord
  has_one_attached :mycar_image
end

app/models/part.rb
class Part < ApplicationRecord
  has_one_attached :parts_image
  belongs_to :user
  # has_many :favorites, dependent: :destroy
  
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
end

app/models/track_event.rb
class TrackEvent < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  # has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :mycar_image
  
  has_many :posts, dependent: :destroy
  has_many :track_events, dependent: :destroy
  has_many :parts, dependent: :destroy
  has_many :my_best_times, dependent: :destroy
  belongs_to :circuit_track, optional: true, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  accepts_nested_attributes_for :my_best_times, allow_destroy: true
  
  has_many :follows, foreign_key: :follower_id, dependent: :destroy

  has_many :followings, through: :follows, source: :followed
  has_many :followers, through: :follows, source: :follower

  def follow(user)
    follows.create(followed_id: user.id)
  end

  def unfollow(user)
    followings.delete(user)
  end

  def following?(user)
    followings.include?(user)
  end
  
  def self.my_followers(user)
    follower_ids = Follow.where(followed_id: user.id).pluck(:follower_id)
    User.where(id: follower_ids)
  end
  
  def deleted?
    is_deleted
  end
  
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :nickname, presence: true
  
  enum main_circuit: { tukubacircuit: 0, fuji_speedway: 1, suzukacircuit: 2, twinringmotegi: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :nickname, :address, :age, :mycar, :main_circuit, :freeprofile])
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/parts_helper.rb
module Admin::PartsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Let's Driving!!!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/639405144b.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      main {
        background-color: #2f2f2f;
      }
      header {
        background-color: #ff3838;
        color: white;
      }
      header a {
        color: white;
      }
      footer {
        background-color: #ff3838;
      }
    </style>
  </head>

  <body class="d-flex flex-column vh-100 ">
    <header>
      <nav class="navbar navbar-expand-lg border">
        <div class="container">
          <a class="navbar-brand" href="/">Let's Driving!!!</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"><i class="fas fa-bars"></i></span>
          </button>
          
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
              <li class="nav-item">
                <%= link_to users_path, class: "btn nav-link", style: "color: white;" do %>
                  <i class="fa fa-users"></i>
                  会員管理
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to posts_path, class: "btn nav-link", style: "color: white;" do %>
                  <i class="fa fa-pencil"></i>
                  投稿管理
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to circuit_tracks_path, class: "btn nav-link", style: "color: white;" do %>
                  <i class="fa fa-map"></i>
                  サーキット管理
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_admin_session_path, method: :delete, class: "btn nav-link", style: "color: white;" do %>
                  <i class="fa fa-sign-out-alt"></i>
                  ログアウト
                <% end %>
              </li>
            <% elsif user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user), class: "btn nav-link", style: "color: white;" do %>
                  <i class="fa fa-user"></i>
                  マイページ
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to parts_path, class: "btn nav-link", style: "color: white;" do %>
                  <i class="fas fa-wrench"></i>
                  パーツレビュー
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to circuit_tracks_path, class: "btn nav-link", style: "color: white;" do %>
                  <i class="fas fa-flag-checkered"></i>
                  サーキット
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to track_events_path, class: "btn nav-link", style: "color: white;" do %>
                  <i class="fa fa-calendar"></i>
                  イベント
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path, class: "btn nav-link", style: "color: white;" do %>
                  <i class="fa fa-users"></i>
                  ユーザーズ（仮）
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class: "btn nav-link", style: "color: white;" do %>
                  <i class="fa fa-sign-out-alt"></i>
                  ログアウト
                <% end %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to circuit_tracks_path, class: "btn nav-link", style: "color: white;" do %>
                  <i class="fas fa-flag-checkered"></i>
                  サーキット
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to track_events_path, class: "btn nav-link", style: "color: white;" do %>
                  <i class="fa fa-calendar"></i>
                  イベント
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_registration_path, class: "btn nav-link", style: "color: white;" do %>
                  <i class="fa fa-user-plus"></i>
                  新規登録
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path, class: "btn nav-link", style: "color: white;" do %>
                  <i class="fa fa-sign-in-alt"></i>
                  ログイン
                <% end %>
              </li>
            <% end %>
            </ul>
        </div>
      </nav>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <div class="container border-top">
        <div class="row no-gutters">
          <div>
            サーキット走行好き向けのSNSです。<br>
            愛車自慢、タイム自慢、パーツ自慢お好きにどうぞ!
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>